name: NASA Project CI
on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clear npm cache
        run: npm cache clean -f
      - name: Use Node.js version 16
        uses: actions/setup-node@v3
        with: 
          node-version: '16.17.0'
      - run: npm install
      - run: npm start --prefix client 
